spring:
  datasource:
    url: jdbc:h2:file:./database
    username: rebelde
    password: rebelde
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8081
